### ISSUE TITLE
Ошибка подключения. Дело в блюм или скрипте?

### ISSUE THREAD

**Issue by aleksei1951** [petyasoft/Blum#12]
Лог ошибки
`09:12:42.08 | SUCCESS | Валидных сессий: 2; Невалидных: 0
Traceback (most recent call last):
  File "C:\Users\xinos\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1086, in create_connection
    raise exceptions[0]
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1070, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 974, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Program Files\Python311\Lib\asyncio\proactor_events.py", line 726, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 854, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 641, in finish_connect
    ov.getresult()
OSError: [WinError 121] Превышен таймаут семафора

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xinos\Desktop\Blum-main\main.py", line 39, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\xinos\Desktop\Blum-main\main.py", line 36, in main
    await asyncio.gather(*tasks)
  File "C:\Users\xinos\Desktop\Blum-main\utils\blum.py", line 39, in main
    await self.login()
  File "C:\Users\xinos\Desktop\Blum-main\utils\blum.py", line 122, in login
    resp = await self.session.post("https://gateway.blum.codes/v1/auth/provider/PROVIDER_TELEGRAM_MINI_APP", json=json_data,proxy = self.proxy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xinos\AppData\Roaming\Python\Python311\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xinos\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xinos\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xinos\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 1257, in _create_direct_connection
    raise last_exc
  File "C:\Users\xinos\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xinos\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 1033, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway.blum.codes:443 ssl:default [Превышен таймаут семафора]`

**Comment by xelinel32** [comment]
Probably this is Blum's problem.
