### ISSUE TITLE
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

### ISSUE THREAD

**Issue by sinkcoder** [petyasoft/Blum#14]
Is this project still works? I've tried proxies from Hong Kong and Russia. And the telegram login is ok.
```
Traceback (most recent call last):
  File "C:\Users\dev\Documents\web3\farm\Blum\main.py", line 39, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "D:\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\dev\Documents\web3\farm\Blum\main.py", line 36, in main
    await asyncio.gather(*tasks)
  File "C:\Users\dev\Documents\web3\farm\Blum\utils\blum.py", line 40, in main
    await self.login()
  File "C:\Users\dev\Documents\web3\farm\Blum\utils\blum.py", line 127, in login
    resp = await self.session.post("https://gateway.blum.codes/v1/auth/provider/PROVIDER_TELEGRAM_MINI_APP", json=json_data, proxy = self.proxy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dev\Documents\web3\farm\Blum\venv\Lib\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dev\Documents\web3\farm\Blum\venv\Lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dev\Documents\web3\farm\Blum\venv\Lib\site-packages\aiohttp\connector.py", line 942, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dev\Documents\web3\farm\Blum\venv\Lib\site-packages\aiohttp\connector.py", line 1329, in _create_proxy_connection
    resp = await proxy_resp.start(conn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dev\Documents\web3\farm\Blum\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dev\Documents\web3\farm\Blum\venv\Lib\site-packages\aiohttp\streams.py", line 640, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

**Comment by sinkcoder** [comment]
solved
