### ISSUE TITLE
proxies are not working, although the session has been added

### ISSUE THREAD

**Issue by veleg** [petyasoft/Blum#15]
20:38:57.96 | SUCCESS | Валидных сессий: 1; Невалидных: 0
**The following error occurs**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_proto.py", line 256, in data_received
    messages, upgraded, tail = self._parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Expected HTTP/:

    b''
      ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
aiohttp.http_exceptions.HttpProcessingError: 0, message:


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/admin/blum/main.py", line 39, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/admin/blum/main.py", line 36, in main
    await asyncio.gather(*tasks)
  File "/home/admin/blum/utils/blum.py", line 39, in main
    await self.login()
  File "/home/admin/blum/utils/blum.py", line 122, in login
    resp = await self.session.post("https://gateway.blum.codes/v1/auth/provider/PROVIDER_TELEGRAM_MINI_APP", json=json_data,proxy = self.proxy)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 942, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1329, in _create_proxy_connection
    resp = await proxy_resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 978, in start
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 0, message='', url=URL('socks5://Mxxx:oxxx@xx.xx.43.105:8000')
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f73b8c7e730>

```

**Comment by petyasoft** [comment]
try change proxy

**Comment by veleg** [comment]
proxies are working. Sessions are created. From another device in elegram I looked at the connected devices, the country of this proxy is displayed. that is, the session was created correctly and from this IP address

**Comment by Artazar13** [comment]
1 Вопрос по мобильным прокси. Если установить один мобильный прокси на все сессии, при переключении на новую сессию будет меняться IP адрес?
2 Спустя время установленное в конфиге время, когда нужно будет зайти боту в сессию по мобильному прокси он поменяет IP адрес?

**Comment by kaospwnz** [comment]
The same error, can you help us, Petya?

**Comment by petyasoft** [comment]
i think blum server dont support this proxy or thix proxy type, thy with another proxy servise

**Comment by Artazar13** [comment]
**Обычно использую gpt4о чтобы понять что да как, вот он мне расписал причины и возможные пути устранения:**

Ошибка, которую ты видишь, связана с использованием прокси-сервера типа SOCKS5. В предоставленном логе ошибка возникает при попытке установить соединение через этот прокси.

Основные причины, по которым могла возникнуть эта ошибка:

Неправильный формат прокси URL: Убедитесь, что URL прокси указан верно. Например: socks5://username:password@proxy_host:proxy_port.

Некорректные учётные данные: Проверьте логин и пароль прокси-сервера. Возможно, они неверные.

Недоступный прокси-сервер: Прокси-сервер может быть недоступен или заблокирован.

Не поддерживаемый формат: Хотя aiohttp поддерживает SOCKS5 прокси, могут быть специфические обстоятельства, при которых SOCKS5 прокси не работает как ожидается.

Для диагностики подтвердите:

Работоспособность прокси с другим инструментом (например, через curl или браузер).
Использование актуальной версии библиотеки aiohttp.
Если нужна помощь с написанием тестового кода для отладки, сообщи об этом.

**Comment by Artazar13** [comment]
Неправильный формат прокси URL: Убедитесь, что URL прокси указан верно. Например: socks5://username:password@proxy_host:proxy_port.

Посмотри, в к config какой тип выбран SOCKS5 или http
