### ISSUE TITLE
Err

### ISSUE THREAD

**Issue by Keyz400** [petyasoft/Blum#60]
![Screenshot_2024-11-06-16-21-26-888_com server auditor ssh client](https://github.com/user-attachments/assets/ed179150-2319-4e0a-9943-bcfa0c01c5da)

**Comment by alex-kiev** [comment]
wasm://wasm/000e1a26:1


RuntimeError: unreachable
    at wasm://wasm/000e1a26:wasm-function[155]:0x29a55
    at wasm://wasm/000e1a26:wasm-function[220]:0x2c7d7
    at wasm://wasm/000e1a26:wasm-function[82]:0x1ae37
    at Object.F [as getPayload] (file:///home/armbian/Blum/utils/payload/blum_worker.mjs:166:15)
    at file:///home/armbian/Blum/utils/payload/blum.mjs:9:22

Node.js v18.19.0
{"message":"cannot decrypt claim payload"} 102
^CTraceback (most recent call last):
  File "/home/armbian/Blum/main.py", line 39, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1884, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)


Similar error
