### ISSUE TITLE
что делать с ошибкой

### ISSUE THREAD

**Issue by SalatikBr** [petyasoft/Blum#8]
установил модуль а ошибка не пропадает 
Traceback (most recent call last):
  File "C:\Users\levbe\OneDrive\Документы\Blum-main\Blum-main\main.py", line 1, in <module>
    from utils.core import create_sessions
  File "C:\Users\levbe\OneDrive\Документы\Blum-main\Blum-main\utils\__init__.py", line 1, in <module>
    from .blum import Blum
  File "C:\Users\levbe\OneDrive\Документы\Blum-main\Blum-main\utils\blum.py", line 1, in <module>
    from pyrogram.raw.functions.messages import RequestWebView
ModuleNotFoundError: No module named 'pyrogram'

**Comment by petyasoft** [comment]
зайди в телеграм в чате спроси tg @petyasofts , попробуй pip install pyrogram

**Comment by SalatikBr** [comment]
я установил модуль щас спрошу в чате
